# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
# tests go here
-   repo: local
    hooks:
    -   id: tests-main
        name: Test main.py
        entry: python test/test_main.py
        language: system
        types: [python]
-   repo: local
    hooks:
    -   id: tests-user-api
        name: Test api/user_api.py
        entry: python test/test_user_api.py
        language: system
        types: [python]
-   repo: local
    hooks:
    -   id: tests-discovery
        name: Test api/discovery.py
        entry: python test/test_discovery.py
        language: system
        types: [python]
-   repo: local
    hooks:
    -   id: tests-instance
        name: Test containerizer/instance.py
        entry: python test/test_instance.py
        language: system
        types: [python]
